### ISSUE TITLE
Scalar Multiplication Algorithms Tracking Issue

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-rs#43]
These are the classic scalar multiplication algorithms:
- [ ] Double-and-add
- [ ] Windowed Double-and-add
- [ ] Sliding-window Double-and-add
- [ ] NAF
- [ ] wNAF
- [ ] Vector Chains
- [ ] Montgomery Ladder
We should implement all the above and provide a uniform interface for applying a specific technique (perhaps a trait which each can implement). Also, we should ensure that each implementation is compiler-independent so we can use it in-circuit.
